### ISSUE TITLE
X-Response-Time 实际上并不输出

### ISSUE THREAD

**Issue by chenxb66** [go-nunu/nunu-layout-advanced#13]
在 internal/middleware/log.go 里面的  

`ctx.Header("X-Response-Time", duration)`

在Handler里面调用了v1.HandleSuccess 或者  v1.HandleError 后，也就是调用了 ctx.JSON 后，

实际上不会输出到客户端。

**Comment by codingcn** [comment]
https://github.com/go-nunu/nunu-layout-advanced/commit/c38bb4e2e5e531b06cadd4d28a1984b7d1f6aa6d

移除了
