### ISSUE TITLE
请问service里分模块怎么办？

### ISSUE THREAD

**Issue by fuyuku** [go-nunu/nunu-layout-advanced#17]
我在repository和service里分别建了相同名字的文件夹，然后就在别处引用的时候就老是混乱，很不方便，有什么好的办法吗？

**Comment by fuyuku** [comment]
可以建议大佬，写一个类似gin-vue-admin的示例工程吗？
那个项目我看了一下，代码一般般，没有大佬的项目结构好
大佬可以写一个出来，会更有人气

**Comment by codingcn** [comment]
文件夹内的包名重新定义下就行，比如xxxrepo。


admin目前没有精力搞的。

**Comment by fuyuku** [comment]
好的谢谢
